# Generated by Django 5.1.7 on 2025-03-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="clothing_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="clothing_images/"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_image",
            field=models.ImageField(blank=True, null=True, upload_to="user_images/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
