# Generated by Django 5.1.7 on 2025-03-20 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
