# Generated by Django 5.1.7 on 2025-03-20 20:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_avatar_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="file",
            field=models.FileField(upload_to=api.models.avatar_file_path),
        ),
    ]
